kind: pipeline
name: default

steps:
  - name: get_dependencies
    image: debian
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
    commands:
      - apt-get update && apt-get install hugo curl python
      - curl -O https://bootstrap.pypa.io/get-pip.py
      - python get-pip.py --user
      - pip install awscli --upgrade --user

trigger:
  branch:
  - master