kind: pipeline
name: default

steps:
  - name: get_dependencies
    image: debian
#    environment:
#      USERNAME:
#        from_secret: username
#      PASSWORD:
#        from_secret: password
    commands:
      - apt-get update && apt-get install hugo curl python
      - curl -O https://bootstrap.pypa.io/get-pip.py
      - python get-pip.py --user
      - pip install awscli --upgrade --user

trigger:
  branch:
  - master