kind: pipeline
name: default

steps:
  - name: get_dependencies
    image: debian
    commands:
      - apt-get update && apt-get install hugo curl python
      - curl -O https://bootstrap.pypa.io/get-pip.py
      - python get-pip.py --user
      - pip install awscli --upgrade --user
