baseURL = "http://legacyoffire.info/"
languageCode = "en-us"
title = "Legacy of Fire"
theme = "gohugo-theme-ananke"
MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = "UA-130579521-1"
enableRobotsTXT = true
disqusShortname = "legacyoffire"